
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/repository01
    username: root
    password: Petrucci93.
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false